.gitignore
HostingerApi.php
HostingerApiException.php

Hostinger Api SDK implemented

---

composer.json

Composer init

---

HostingerApi.php

Add getClientByEmailAndPassword method

---

HostingerApi.php

Client password remind implemented

---

HostingerApi.php

Fixed "A non well formed numeric value encountered" error

---

HostingerApi.php
composer.json

Composer.json updates

---

HostingerApi.php

create cartOrderCreate function

create cartOrderCreate function

---

HostingerApi.php

Add isset to $_SERVER['HTTP_X_FORWARDED_FOR'] at getIp()
@hostinger/devs

Add isset to $_SERVER['HTTP_X_FORWARDED_FOR'] at getIp()

---

HostingerApi.php

@hostinger/devs will be used for cart client social login

clientGetByLoginHash method added

---

HostingerApi.php

oauthProviderGetList method added

---

HostingerApi.php

oauthProviderGetList method fix

---

HostingerApi.php

Add clientWhoisProfileCreate method

---

HostingerApi.php

Get validation errors added

---

HostingerApi.php

Get country & phone code list

---

HostingerApi.php

Add domainIsAvailable method

---

HostingerApi.php
composer.json

Send mail events via API call, and then to mailer

---

HostingerApi.php

https://github.com/hostinger/youhosting/issues/799 @hostinger/devs

added new call knowledgeBaseGetList

---

HostingerApi.php

https://github.com/hostinger/youhosting/issues/344 @hostinger/devs

Add campaign param to cart order create

---

HostingerApi.php

Api call to  create client & buy domain 
@hostinger/devs

added create-order-with-client api call

---

HostingerApi.php

Autologin api call

---

HostingerApi.php

@hostinger/devs method to get approved reviews. This is already used in weblink and will be on new site

Add get reviews method

---

HostingerApi.php
composer.json

Get cart catalog

---

HostingerApi.php

Add multi login endpoint

---

HostingerApi.php

Add happiness_score endpoint
issue https://github.com/hostinger/hostinger/issues/1085

Add happiness_score endpoint

---

HostingerApi.php

Endpoint to check if domain is registered at Hostinger
calls https://github.com/hostinger/hostinger/pull/2184

Endpoint is domain is registered at Hostinger

---

HostingerApi.php

related https://github.com/hostinger/www-sites/pull/2226

Accept affiliate subid

---

HostingerApi.php

related https://github.com/hostinger/global/issues/4246

Get client by email oauth

---

HostingerApi.php

related https://github.com/hostinger/hostinger/pull/3020

Unlink social by email

---

HostingerApi.php

If additional params are needed, allow to send them

Add additional params to public ticket create

---

HostingerApi.php

related https://github.com/hostinger/www-sites/pull/2896

Add create public ticket Intercom function

---

HostingerApi.php

Pass 000webhost user ID on order create

Pass 000webhost user ID on order create

---

HostingerApi.php

related https://github.com/hostinger/hostinger/pull/4040

Allow free trial by email check

---

HostingerApi.php

https://github.com/hostinger/marketing/issues/767

Send Hasoffers session

---

HostingerApi.php

https://github.com/hostinger/hostinger/issues/4391

Add auth webmail call

---

HostingerApi.php

https://github.com/hostinger/crm/issues/509

Add server list parsing method

---

HostingerApi.php

Add a call to update payment confirmation.

Add updatePaymentConfirmation method

---

HostingerApi.php

related https://github.com/hostinger/cs-ideas/issues/172

Changed api call according to new update logic

---

HostingerApi.php

references https://github.com/hostinger/crm/issues/914

Store new migration function added

---

HostingerApi.php

reseller_client_order_id param added to storeNewMigrationRequest

reseller_client_order_id param added to storeNewMigrationRequest

---

HostingerApi.php

https://github.com/hostinger/global/issues/16753

Feature: api call to retry GDPR deletion process

---

HostingerApi.php

Add file manager URL endpoint

---

HostingerApi.php

https://github.com/hostinger/global/issues/21963

GDPR: rest call to stop GDPR deletion proccess
